### ISSUE TITLE
Typo in Data Prep

### ISSUE THREAD

**Issue by bocekout** [learn-co-curriculum/dsc-colab#4]
## Link to Canvas

https://learning.flatironschool.com/courses/8260/pages/using-colab?module_item_id=708098

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

## Describe the Issue
Just a typo: Drop the data into the pane from where you have the data stored and you'll get a warning that the data will be deleted _from the runtime is terminated_; the data is still safe where you have saved it and the notebook file itself will save 

![Screenshot 2024-08-17 164355](https://github.com/user-attachments/assets/bff2ae45-897b-446b-9e2f-80b2bdd01f2e)

### Source

```

```

## (Optional) Proposed Solution

Could be either "deleted when the runtime is terminated" or "deleted from the runtime when it is terminated"

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

Obviously not a big deal, the meaning is not even unclear, it's just a typo.

**Comment by bocekout** [comment]
Found a second typo:

![Screenshot 2024-08-17 165550](https://github.com/user-attachments/assets/de25325c-ab0b-4b82-a7f3-9ec99134ac71)

For this one I would write "Simply open chrome and go to..." or "Use chrome and go to"

**Comment by bpurdy-ds** [comment]
Thank you flagging this issue. We'll take a look.

**Comment by bpurdy-ds** [comment]
The first issue is the phraseology from Google, so there is nothing we can do about that one. :)
Fixed the second one, good suggestion.
